server:
  port: 8800

spring:
  application:
    name: grace-dept
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://39.105.206.67:3306/crazy              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  servlet:
    multipart:
      enabled: false
      max-file-size: 5MB
      max-request-size: 10MB

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lgz.crazy
  mapper-locations: classpath:mybatis/mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 39.105.206.67:22122
  pool:
    jmx-enabled: false